### PR TITLE
an attempt to merge all PRs

### PR DESCRIPTION
**Pull request by tschaume**
- merges #2 #3 #4 #5 #6 #7 #8 #9 #10 #11 #12 
- fixes tests (python2.7 and toasted backend fail)

### CODE REVIEW

**Comment by Manuelraa** [comment]
@tschaume Hey what is the status of this? Would like to use the new marshmallow version for my project. Can u give me an estimate how long u gonna need for this?

**Comment by tschaume** [comment]
@Manuelraa it's done as far as I'm concerned. I'm not using python2.7 or the toasted backend, so haven't looked into fixing the according tests. I'm using the version in this PR as part of the  [MPContribs API](https://github.com/materialsproject/MPContribs/blob/dev/mpcontribs-api/requirements.txt). All good so far 😃

**Comment by Manuelraa** [comment]
Okay thats good to hear! But that sadly also means this project is not activly maintained anymore (last commit 2017)

**Comment by tschaume** [comment]
@touilleMan any interest/plan to review and merge this? @qcho

**Comment by touilleMan** [comment]
@tschaume sorry, I totally stopped working on mongoengine.
I can give you admin access on the repo if you're interested in maintaining it though ;-)

**Comment by tschaume** [comment]
Sure, why not :) Thanks @touilleMan! I'll also need permissions to release on PyPI.

**Comment by qcho** [comment]
My intent on making this compatible with v3 was so long ago. But I did a review comparing the two branches and seems fine.

**Comment by touilleMan** [comment]
Congratulation, you're now maintainer @tschaume  😄 🎉 🎂

**Pull request merged**
